plugins:
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Lint/SuppressedException:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
