name: Build

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.4"
      - name: Tailwind CSS build
        run: bundle exec tailwindcss -m -i src/css/input.css -o static/css/output.css
      - name: Build site
        run: bundle exec rake build
