name: Build and deploy site

on: push

jobs:
  build_site:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install Ruby dependencies
        run: bundle install
      - name: Build site
        run: ./build-site
      - name: Save site artifacts
        uses: actions/upload-artifact@v1
        with:
          name: built-site
          path: build

  deploy_site:
    name: Deploy site
    runs-on: ubuntu-latest
    needs: build_site
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Download site artifacts
        uses: actions/download-artifact@v1
        with:
          name: built-site
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: built-site
          SINGLE_COMMIT: true
