name: Build & Deploy kickstarterunited.org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.4"
      - name: Tailwind CSS build
        run: bundle exec tailwindcss -m -i src/css/input.css -o static/css/output.css
      - name: Build site
        run: bundle exec rake build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          single-commit: true
